// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: answers.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (question_id, text, is_correct) 
VALUES ($1, $2, $3) RETURNING id, question_id, text, is_correct, created_at
`

type CreateAnswerParams struct {
	QuestionID int32
	Text       string
	IsCorrect  bool
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error) {
	row := q.db.QueryRowContext(ctx, createAnswer, arg.QuestionID, arg.Text, arg.IsCorrect)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const getAnswerByQuestionAndText = `-- name: GetAnswerByQuestionAndText :one
SELECT id, question_id, text, is_correct, created_at FROM answers
WHERE question_id = $1 AND text = $2
LIMIT 1
`

type GetAnswerByQuestionAndTextParams struct {
	QuestionID int32
	Text       string
}

func (q *Queries) GetAnswerByQuestionAndText(ctx context.Context, arg GetAnswerByQuestionAndTextParams) (Answer, error) {
	row := q.db.QueryRowContext(ctx, getAnswerByQuestionAndText, arg.QuestionID, arg.Text)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Text,
		&i.IsCorrect,
		&i.CreatedAt,
	)
	return i, err
}

const getTestCorrectAnswers = `-- name: GetTestCorrectAnswers :many
SELECT 
    q.id AS question_id, 
    a.id AS answer_id
FROM questions q
JOIN answers a ON q.id = a.question_id
WHERE q.test_id = $1 AND a.is_correct = TRUE
`

type GetTestCorrectAnswersRow struct {
	QuestionID int32
	AnswerID   int32
}

func (q *Queries) GetTestCorrectAnswers(ctx context.Context, testID uuid.UUID) ([]GetTestCorrectAnswersRow, error) {
	rows, err := q.db.QueryContext(ctx, getTestCorrectAnswers, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTestCorrectAnswersRow
	for rows.Next() {
		var i GetTestCorrectAnswersRow
		if err := rows.Scan(&i.QuestionID, &i.AnswerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAnswersByQuestionIDs = `-- name: ListAnswersByQuestionIDs :many
SELECT id, question_id, text, is_correct, created_at FROM answers WHERE question_id = ANY($1::int[]) ORDER BY id
`

func (q *Queries) ListAnswersByQuestionIDs(ctx context.Context, questionIds []int32) ([]Answer, error) {
	rows, err := q.db.QueryContext(ctx, listAnswersByQuestionIDs, pq.Array(questionIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Text,
			&i.IsCorrect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
