// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: examples.sql

package db

import (
	"context"
	"time"
)

const createExample = `-- name: CreateExample :one
INSERT INTO examples (name, description, full_example, created_at) 
VALUES ($1, $2, $3, $4) RETURNING id, name, description, full_example, created_at
`

type CreateExampleParams struct {
	Name        string
	Description string
	FullExample string
	CreatedAt   time.Time
}

func (q *Queries) CreateExample(ctx context.Context, arg CreateExampleParams) (Example, error) {
	row := q.db.QueryRowContext(ctx, createExample,
		arg.Name,
		arg.Description,
		arg.FullExample,
		arg.CreatedAt,
	)
	var i Example
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FullExample,
		&i.CreatedAt,
	)
	return i, err
}

const listExamples = `-- name: ListExamples :many
SELECT id, name, description, full_example, created_at FROM examples 
ORDER BY created_at DESC
`

func (q *Queries) ListExamples(ctx context.Context) ([]Example, error) {
	rows, err := q.db.QueryContext(ctx, listExamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Example
	for rows.Next() {
		var i Example
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.FullExample,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
