// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	UserName  string
	Email     string
	Password  string
	UserTest  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}
