// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: questions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (test_id, text, multiple) 
VALUES ($1, $2, $3) RETURNING id, test_id, text, multiple, created_at
`

type CreateQuestionParams struct {
	TestID   uuid.UUID
	Text     string
	Multiple bool
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, createQuestion, arg.TestID, arg.Text, arg.Multiple)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.Text,
		&i.Multiple,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionByTestAndText = `-- name: GetQuestionByTestAndText :one
SELECT id, test_id, text, multiple, created_at FROM questions
WHERE test_id = $1 AND text = $2
LIMIT 1
`

type GetQuestionByTestAndTextParams struct {
	TestID uuid.UUID
	Text   string
}

func (q *Queries) GetQuestionByTestAndText(ctx context.Context, arg GetQuestionByTestAndTextParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByTestAndText, arg.TestID, arg.Text)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.TestID,
		&i.Text,
		&i.Multiple,
		&i.CreatedAt,
	)
	return i, err
}

const listQuestionsByTestID = `-- name: ListQuestionsByTestID :many
SELECT id, test_id, text, multiple, created_at FROM questions WHERE test_id = $1 ORDER BY id
`

func (q *Queries) ListQuestionsByTestID(ctx context.Context, testID uuid.UUID) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionsByTestID, testID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.TestID,
			&i.Text,
			&i.Multiple,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
