// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: theories.sql

package db

import (
	"context"
	"time"
)

const createTheory = `-- name: CreateTheory :one
INSERT INTO theories (name, description, theoryFull, created_at) 
VALUES ($1, $2, $3, $4) RETURNING id, name, description, theoryfull, created_at
`

type CreateTheoryParams struct {
	Name        string
	Description string
	Theoryfull  string
	CreatedAt   time.Time
}

func (q *Queries) CreateTheory(ctx context.Context, arg CreateTheoryParams) (Theory, error) {
	row := q.db.QueryRowContext(ctx, createTheory,
		arg.Name,
		arg.Description,
		arg.Theoryfull,
		arg.CreatedAt,
	)
	var i Theory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Theoryfull,
		&i.CreatedAt,
	)
	return i, err
}

const listTheories = `-- name: ListTheories :many
SELECT id, name, description, theoryFull, created_at FROM theories 
ORDER BY created_at DESC
`

func (q *Queries) ListTheories(ctx context.Context) ([]Theory, error) {
	rows, err := q.db.QueryContext(ctx, listTheories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theory
	for rows.Next() {
		var i Theory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Theoryfull,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
